version: "3.3"
services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379

volumes:
  redis_volume_data:
  redis_insight_volume_data:
